### ISSUE TITLE
Support Voxel Sizes?

### ISSUE THREAD

**Issue by jinbyeong** [pboutinaud/SHiVAi#1]
Hello, thank you for your excellent work and research.

Could you please let me know the range of voxel sizes that this preprocessing process supports? In my case, I have T1 images with sizes of 1024x1024x175 and 512x512x208.

Thank you!

**Comment by VN-Fealinx** [comment]
Hi, 
The preprocessing will always re-sample the input to 1x1x1mm^3 isotropic (what the AI segmentation algorithm is expecting). So whatever the input (as long as the resolution is not too low) it should work.
We haven't tested with the specific image sizes that you are asking about, but I think it should work.
Let us know if you have any problem :)
Cheers,
Victor

**Comment by VN-Fealinx** [comment]
Another thing to note: we just realized there was a small bug in the code for images with non-isotropic voxel. We patched it now but be mindful of the version: the patch was now live in version 0.4.2 of the pipeline (and the updated apptainer image is also named shiva_0.4.2.sif).
